version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autoria
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    env_file: .env
    volumes:
      - ./dumps:/app/dumps
      - .:/app
    depends_on:
      - db
    working_dir: /app
    command: ["python", "main.py"]

volumes:
  pgdata:
